### ISSUE TITLE
OceanShader.tres is missing

### ISSUE THREAD

**Issue by younespyco** [SIsilicon/Godot-Ocean-Demo#1]
Hello
The asset didn't work for me , when i try to open it , it said that OceanShader.tres is missing : here are the screenshots : 
[https://bit.ly/2s2UiRS](url)
and when i try to skip this and launch it i receive this error  : 
[https://bit.ly/2x6xs1M](url)
Many thanks
pyco

**Comment by SIsilicon** [comment]
Well that's because I forgot to upload that shader _before_ I uploaded the demo to the asset store. Download directly from github for now and you should be fine.
