### ISSUE TITLE
OceanShader.tres has broken dependencies: noise_tileable.png

### ISSUE THREAD

**Issue by MikeFair** [SIsilicon/Godot-Ocean-Demo#2]
Attempted to clone from repository and import/edit the godot.project file and received the error.
```
Scene 'res://OceanShader.tres' has broken dependencies:
    res://noise_tileable.png::Texture
```

![image](https://user-images.githubusercontent.com/2304557/40872698-5741dd8c-6607-11e8-8222-b32806622790.png)

**Comment by SIsilicon** [comment]
Ok. I have uploaded the missing file. Thanks for telling me.
