### ISSUE TITLE
Error after running Godot-Ocean-Demo

### ISSUE THREAD

**Issue by silocoder** [SIsilicon/Godot-Ocean-Demo#4]
Not sure if this project is still active but found an issue

https://github.com/godotengine/godot/issues/43666

**Comment by SIsilicon** [comment]
As a matter of fact, this project is no longer maintained.
I do not plan to update this, as I've discovered better ways to make oceans in realtime.
I'll archive this now. You'll have to look for something else. Thanks for taking a look though. :)
